#Route pour les vues de base (index)
index :
    pattern:  /
    defaults: { _controller: UserBundle:Index:index }

# Route pour la gestion des comptes bancaires
creerCompte:
    pattern:  /compte/creer
    defaults: { _controller: UserBundle:Compte:creer }

modifCompte:
    pattern: /compte/modif/{id}
    defaults: {_controller: UserBundle:Compte:modif}

supprCompte:
    pattern: /compte/suppr/{id}
    defaults: {_controller: UserBundle:Compte:suppr}

montrerCompte:
    pattern: /compte/affich
    defaults: {_controller: UserBundle:Compte:show}

# Route pour la gestion des opérations bancaires
creerOperation:
    pattern:  /opbancaire/creer/{id}
    defaults: { _controller: UserBundle:OpBancaire:creer }

supprOperation:
    pattern:  /opbancaire/suppr/{id}
    defaults: { _controller: UserBundle:OpBancaire:suppr }


