#Route pour les vues de base (index)
index :
    pattern:  /
    defaults: { _controller: UserBundle:Index:index }

# Route pour la gestion des comptes bancaires
creerCompte:
    pattern:  /compte/creer
    defaults: { _controller: UserBundle:Compte:creer }

modifCompte:
    pattern: /compte/modif/{id}
    defaults: {_controller: UserBundle:Compte:modif}

supprCompte:
    pattern: /compte/suppr/{id}
    defaults: {_controller: UserBundle:Compte:suppr}

montrerCompte:
    pattern: /compte/affich
    defaults: {_controller: UserBundle:Compte:show}

detailCompte:
    pattern: /compte/{id}
    defaults: {_controller: UserBundle:Compte:detail}


# Route pour la gestion des opérations bancaires
creerOperation:
    pattern:  /opbancaire/creer/{id}
    defaults: { _controller: UserBundle:OpBancaire:creer }

supprOperation:
    pattern:  /opbancaire/suppr/{id}
    defaults: { _controller: UserBundle:OpBancaire:suppr }

# Route pour la gestion des seuils des comptes

creerSeuil:
    pattern:  /seuil/creer/{id}
    defaults: { _controller: UserBundle:Seuil:creer }

modifSeuil:
  pattern:  /seuil/modif/{id}
  defaults: { _controller: UserBundle:Seuil:modif }


