creerCompte:
    pattern:  /compte/creer
    defaults: { _controller: UserBundle:Compte:creer }

modifCompte:
    pattern: /compte/modif/{id}
    defaults: {_controller: UserBundle:Compte:modif}

supprCompte:
    pattern: /compte/suppr/{id}
    defaults: {_controller: UserBundle:Compte:suppr}

creerOperation:
    pattern:  /opbancaire/creer/{id}
    defaults: { _controller: UserBundle:OpBancaire:creer }
